### development only
version: '3.8'
services:
  mongo:
    image: 'mongo:latest'
    container_name: mongo
    volumes:
      - ./.mongo-volume:/data/db
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=test
      - MONGO_INITDB_ROOT_PASSWORD=test
  api:
    container_name: api
    build:
      context: .
      dockerfile: 'Dockerfile'
    command: ['yarn', 'start']
