name: CD
on:
  push:
    branches:
      - master
      - dev
env:
  REGISTRY: registry.cybr.ovh/voilasnap
jobs:
  build-deploy:
    name: Build docker image and deploy
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull latest docker images from registry
        run: |-
          docker pull "$REGISTRY/voilasnap-api-deps:latest" || true
          docker pull "$REGISTRY/voilasnap-api-final:latest" || true
      - name: Build docker images
        run: |-
          docker build \
            --cache-from "$REGISTRY/voilasnap-api-deps:latest" \
            --tag $REGISTRY/voilasnap-api-deps:latest \
            .
          docker build \
            --cache-from "$REGISTRY/voilasnap-api-deps:latest" \
            --cache-from "$REGISTRY/voilasnap-api-final:latest" \
            --tag $REGISTRY/voilasnap-api-final:latest \
            .
      - name: Push images to registry
          run: |-
            docker push "$REGISTRY/voilasnap-api-deps:latest"
            docker push "$REGISTRY/voilasnap-api-final:latest"