name: CD
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy to server
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: multiple command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_DEPLOY_HOST }}
          username: ${{ secrets.SSH_DEPLOY_USERNAME }}
          key: ${{ secrets.SSH_DEPLOY_KEY }}
          port: ${{ secrets.SSH_DEPLOY_PORT }}
          script: |
            cd ~/voilasnap-api
            git pull origin master
            yarn install --frozen-lockfile
            yarn build
            pm2 restart voilasnap-api
