name: CD
on:
  push:
    branches:
      - master
      - dev
env:
  REGISTRY: registry.cybr.ovh:5000/voilasnap
jobs:
  build-docker-image:
    name: Build docker image
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull latest docker images from registry
        run: |-
          docker pull "${{ env.REGISTRY }}/voilasnap-api-deps:latest" || true
          docker pull "${{ env.REGISTRY }}/voilasnap-api-final:latest" || true
      - name: Build docker images
        run: |-
          docker build \
            --target dependencies \
            --cache-from "${{ env.REGISTRY }}/voilasnap-api-deps:latest" \
            --tag "${{ env.REGISTRY }}/voilasnap-api-deps:latest" \
            .
          docker build \
            --cache-from "${{ env.REGISTRY }}/voilasnap-api-deps:latest" \
            --cache-from "${{ env.REGISTRY }}/voilasnap-api-final:latest" \
            --tag "${{ env.REGISTRY }}/voilasnap-api-final:latest" \
            .
      - name: Push images to registry
        run: |-
          docker push "${{ env.REGISTRY }}/voilasnap-api-deps:latest"
          docker push "${{ env.REGISTRY }}/voilasnap-api-final:latest"
  deploy:
    name: Deploy to server
    needs: build-docker-image
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: multiple command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_DEPLOY_HOST }}
          username: ${{ secrets.SSH_DEPLOY_USERNAME }}
          key: ${{ secrets.SSH_DEPLOY_KEY }}
          port: ${{ secrets.SSH_DEPLOY_PORT }}
          script: |-
            docker pull "${{ env.REGISTRY }}/voilasnap-api-final:latest" || true
            docker stop voilasnap-api || true
            docker rm voilasnap-api || true
            docker run --restart=always \
              -d "${{ env.REGISTRY }}/voilasnap-api-final:latest" \
              --network=traefik \
              --name=voilasnap-api \
              -e JWT_SECRET="${{ secrets.API_JWT_SECRET }}" \
              -e MONGODB_CONNECTION_STRING="${{ secrets.API_MONGO_URI }}" \
              -e NODE_ENV="production" \
              -e PORT=51149 \
              -l "traefik.enable=true" \
              -l "traefik.frontend.rule=Host:voilasnap.cf" \
              -l "traefik.backend=voilasnap-api" \
              -l "traefik.port:51149" \
              -l "traefik.frontend.entryPoints=http" \
              -p 51149:51149